Add docker for server and database
JirenMTA/dotnet-2023 pull request #13
Opened 2023-07-05 18:42 UTC by JirenMTA

2023-07-05 19:24 UTC, JirenMTA commented
Проверьте, пожалуйста ещё файл [.github/workflow/TestLibrarySchool.yml](https://github.com/JirenMTA/dotnet-2023/blob/main/.github/workflows/TestLibrarySchool.yml). Я это делал сразу в ветки `main` а не в отдельной ветке

2023-07-06 10:06 UTC, alxmcs requested changes
Касательно ci/cd - насколько я вижу, тесты успешно исполняются: ![image](https://github.com/JirenMTA/dotnet-2023/assets/70561974/5e7d92b2-98d7-434a-8354-9cea742eed26)

docker-compose.yml осталось немного докрутить

2023-07-06 10:06 UTC, alxmcs commented on docker-compose.yml
> +  database:
Базе надо подкинуть volume, чтобы данные сохранялись, а не пропадали со смертью контейнера
Пример можно глянуть [тут](https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql)

2023-07-06 10:06 UTC, alxmcs commented on docker-compose.yml
> +  server:
Сервер было бы неплохо на всякий случай рестартить, если он упал.
Пример [тут](https://www.baeldung.com/ops/docker-compose-restart-policies).

2023-07-06 10:06 UTC, alxmcs commented on docker-compose.yml
> +  database:
Базе данных было бы неплохо заэкспозить порт наружу, чтобы была возможность посмотреть на данные

2023-07-06 13:15 UTC, alxmcs approved these changes

2023-07-06 13:15 UTC, merged